apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-rc
  labels:
    name: mysql-rc
spec:
  replicas: 1
  selector:
    name: mysql-apps
  template:
    metadata:
      labels:
        name: mysql-apps
    spec:
      nodeName: k8s-agentpool1-72890096-1
      containers:
      - name: mysql-app
        image: r.fds.so:5000/harbor-db:0.5.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom: 
              configMapKeyRef: 
               name: harbor-mysql-config
               key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        hostPath:
          path: /data/harbor/mysql
#        persistentVolumeClaim:
#          claimName: storage-pvc 
